### PR TITLE
Import all projects

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Importing all projects works now !

# Changes

## Dnanexus utilities
- check if a project is archived

## Multiqc report
- check if the report assay exists and assign importable status depending on the result
- use regex to find sample id
- if date format is wrong, use job date for the date of the run
- handle NA when found in the tool fields
- check if fastqc link table gets created

## Tool
- pass the multiqc field name to the tool
- check all the fields for a tool. If we have some but not all, add them with NAs

## initial import
- Import only importable reports

## assays.json
- add TSOE and FH assays

## fastqc.json
- typo in the `per_sequence_quality_score` field

## picard.json
- add `duplication_metrics` tool for picard for TSOE and FH

## models
- a bunch of null and blank for various fields
- `duplication_metrics` model

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 146 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc33TzAA6AJHmFp5gmm:-Nc33TzAA6AJHmFp5gmn:b-4z1bhj) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L146)):*
> ```Python
>                         read = match.groupdict()["read"]
>                     else:
>                         # give up on the samples that don't have lane and read
> ```

quality comment



_Code quote:_
```Python
 give up on the samples that don't have lane and read
```
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 167 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35B6l6Fdvrb7IMQz7:-Nc35B6l6Fdvrb7IMQz8:b-6ys0qn) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L167)):*
if you need to remove multiple strings (or replace with the same) then `re.sub` can be nicer:
```
>>> sample
'sample1_INDEL_PASS_INDEL_ALL'

>>> re.sub('_INDEL_PASS|_INDEL_ALL|_SNP_PASS|_SNP_ALL', "", sample)
'sample1'
```



_Code quote:_
```Python
                        for suffix in [
                            "_INDEL_PASS", "_INDEL_ALL", "_SNP_PASS", "_SNP_ALL"
                        ]:
                            if suffix in sample:
                                sample = sample.replace(suffix, "")
```
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc35bWFAEYxi3ugk31v:bjmf38w) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
> ```Python
>                 # the read
>                 if tool_name == "fastqc":
>                     self.data[sample_id][tool_obj][f"{lane}_{read}"] = cleaned_data
> ```

if there's no match above lane and read are empty strings, so this field will become just an underscore, do you want this?



_Code quote:_
```Python
                if tool_name == "fastqc":
                    self.data[sample_id][tool_obj][f"{lane}_{read}"] = cleaned_data
```
___
*[`trendyqc/trend_monitoring/management/commands/_tool.py` line 101 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc36qDyDIFFp10xLjUr:-Nc36qDz4XpP_3rtV5sE:b9sq6po) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_tool.py#L101)):*
> ```Python
>                     converted_data[field] = "NA"
> 
>         return converted_data
> ```

if all fields are not present do you not also want to handle this?



_Code quote:_
```Python
        # bool to know if all fields are present
        fields_all_present = all(check_fields)
        # bool to know if we have at least one field
        some_fields_present = any(check_fields)

        # check if we have some fields but not all
        if not fields_all_present and some_fields_present:
            # some tools don't provide all the fields they are supposed to
            # provide so check if we have all the fields that we want and add
            # them if we are missing them
            for field in self.fields.values():
                if field not in converted_data:
                    converted_data[field] = "NA"

        return converted_data
```
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc37GR08tdeFgA_yKKc:-Nc37GR19E_wnDx2lSb-:bhvc836) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/initial_import.py#L58)):*
> ```Python
>                 if is_archived(report_object):
>                     # TO-DO: logging system. Generate list of projects skipped
>                     # to allow user to unarchive those to import in database ?
> ```










  _**yes**_



_Code quote:_
```Python
                    # TO-DO: logging system. Generate list of projects skipped
                    # to allow user to unarchive those to import in database ?
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 146 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc33TzAA6AJHmFp5gmm:-Nc6iB_k1WlBED9whygX:byht65b) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L146)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

quality comment
</blockquote></details>

you need to have fun in the code
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 167 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35B6l6Fdvrb7IMQz7:-Nc6h4ww5X9kn6mUA_7r:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L167)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you need to remove multiple strings (or replace with the same) then `re.sub` can be nicer:
```
>>> sample
'sample1_INDEL_PASS_INDEL_ALL'

>>> re.sub('_INDEL_PASS|_INDEL_ALL|_SNP_PASS|_SNP_ALL', "", sample)
'sample1'
```
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc6h8dL7xlfiNWHbKXO:ba5ikz1) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if there's no match above lane and read are empty strings, so this field will become just an underscore, do you want this?
</blockquote></details>

i thought about that but i don't really have a good solution.
realistically, samples that are like that will have a bad sample name.
Now you making me think i should maybe add the sample file name in the individual tables just for more clarity
___
*[`trendyqc/trend_monitoring/management/commands/_tool.py` line 101 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc36qDyDIFFp10xLjUr:-Nc6i3gq4BgCQdGzNwoq:b-u7w2wn) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_tool.py#L101)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if all fields are not present do you not also want to handle this?
</blockquote></details>

if no fields are present, it should return an empty dict which i think is fine
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc37GR08tdeFgA_yKKc:-Nc6iAnf2Udp65Eigq2V:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/initial_import.py#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

_**yes**_
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 167 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35B6l6Fdvrb7IMQz7:-Nc6v8tK0flrIp05eVUt:bqb3di1) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L167)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you leaving it as a loop of replaces or you just not pushed?
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc6uVZX6ktetnsj8icY:bus54t2) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i thought about that but i don't really have a good solution.
realistically, samples that are like that will have a bad sample name.
Now you making me think i should maybe add the sample file name in the individual tables just for more clarity
</blockquote></details>

if this is coming from samples that have failed and have no reads => no fastqs, should you even be storing anything for them? will it not just all be null?

also what do you mean sample file name? as in the full fastq suffix?

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 167 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35B6l6Fdvrb7IMQz7:-Nc71v5gDoZguoVpCYv4:b-ss14t8) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L167)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you leaving it as a loop of replaces or you just not pushed?
</blockquote></details>

i did not push
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc71yiJA5ipYGkFziAV:b-4xkl9o) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if this is coming from samples that have failed and have no reads => no fastqs, should you even be storing anything for them? will it not just all be null?

also what do you mean sample file name? as in the full fastq suffix?
</blockquote></details>

i'd rather store everything and not need it later. Maybe we can apply some filtering the views if we don't want to see them
as in the actual file the data comes from i.e. `sample-id_S34_L001_R1.fastq.gz` or `sample-id.somalier` or whatever else

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc72YbZASP6dTnx_9Ue:b-jn5589) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'd rather store everything and not need it later. Maybe we can apply some filtering the views if we don't want to see them
as in the actual file the data comes from i.e. `sample-id_S34_L001_R1.fastq.gz` or `sample-id.somalier` or whatever else
</blockquote></details>

I think that makes sense for provenance of the values if we need to trace anything back, you going to do it now or add it to the todos?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc73d4J-x0C575OhSBe:b8g10ez) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think that makes sense for provenance of the values if we need to trace anything back, you going to do it now or add it to the todos?
</blockquote></details>

todos probably

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc75uTLEWlhbbH_0l5u:bb7m07t) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

todos probably
</blockquote></details>

okay

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 187 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/22#-Nc35bWFAEYxi3ugk31u:-Nc766AI5peB_hAYcH37:b-404omq) ([raw file](https://github.com/eastgenomics/trendyQC/blob/75c8cf3e7d34a962df130a5bc9d17237ddc64b80/trendyqc/trend_monitoring/management/commands/_multiqc.py#L187)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

okay
</blockquote></details>

i have a lot of todos

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
