### PR TITLE
Fix some issues with the import of all the assays

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Use transaction atomic when saving data
- Fix typos in the config for sompy
- Changes in the models to allow some flexibility in the import of data

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/17)

### CODE REVIEW

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/17)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 239 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/17#-Nal6A3k1BYhhKlLMNZU:-Nal89o79N_AP3XQYIqp:bldpt96) ([raw file](https://github.com/eastgenomics/trendyQC/blob/500695a66e35da9ca85c9fd8e99e6b89832e65ab/trendyqc/trend_monitoring/management/commands/_multiqc.py#L239)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this in the actual Picard data or just in the multiQC (i.e. is multiQC munging this)?

If its in the Picard data it might be worth opening an issue to get an answer, would be good to understand what it means and if its appropriate to make it missing: https://github.com/broadinstitute/picard 
</blockquote></details>

Definitely Picard and it looks like it's a deliberate choice
https://sourceforge.net/p/samtools/mailman/samtools-help/thread/CAEwHMLEAdhWd-C+ELWHZ00NQ5B=UbpK-0DLD21EZjvNL7WOSPQ@mail.gmail.com/
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 270 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/17#-Nal6qr807NFlHJ-KhuX:-Nal8eDu4sUSXeoanR_6:b69xyl1) ([raw file](https://github.com/eastgenomics/trendyQC/blob/500695a66e35da9ca85c9fd8e99e6b89832e65ab/trendyqc/trend_monitoring/management/commands/_multiqc.py#L270)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what does `self.data` look like? I think this might need some thinking about to ensure we don't mix anything up
</blockquote></details>

```
{
    "sample_id": {
        "tool":
            {
                "field": data
            }
     }
}
```
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 288 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/17#-Nal77bZ4cjouk-LVZkP:-Nal8v8sAniNtHnRBycO:b-soh0au) ([raw file](https://github.com/eastgenomics/trendyQC/blob/500695a66e35da9ca85c9fd8e99e6b89832e65ab/trendyqc/trend_monitoring/management/commands/_multiqc.py#L288)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

will this result in duplicates adding to `data_to_remove`? will this break the del lower down?
</blockquote></details>

i think you're talking about having a sample name being present in another and then the other being present in the first if you see what i mean but it can't happen because i check if they are identical i.e.
`NA12878` is in `NA12878-NA12878-1-TWE-F-EGG4` but `NA12878-NA12878-1-TWE-F-EGG4` can't be in `NA12878`

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/17)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 270 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/17#-Nal6qr807NFlHJ-KhuX:-NalDJ9eDQuhUqRvq1On:b707507) ([raw file](https://github.com/eastgenomics/trendyQC/blob/500695a66e35da9ca85c9fd8e99e6b89832e65ab/trendyqc/trend_monitoring/management/commands/_multiqc.py#L270)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

```
{
    "sample_id": {
        "tool":
            {
                "field": data
            }
     }
}
```
</blockquote></details>

can you be explicit since this is a dict and use `self.data.keys()`

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/17)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 270 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/17#-Nal6qr807NFlHJ-KhuX:-NalFYQh-3A01v3xYlk-:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/500695a66e35da9ca85c9fd8e99e6b89832e65ab/trendyqc/trend_monitoring/management/commands/_multiqc.py#L270)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you be explicit since this is a dict and use `self.data.keys()`
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/17)* status: 3 of 4 files reviewed, 1 unresolved discussion

**Pull request merged**
