### PR TITLE
Get sequencer id data

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/19)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/19)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 158 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/19#-Nb-1dvdEsx7_kBG7N1W:-Nb-1dve3CjgvaNlIPGN:bxk6uxf) ([raw file](https://github.com/eastgenomics/trendyQC/blob/090761defd7a06b78602b0b44180d16058642c6c/trendyqc/trend_monitoring/management/commands/_multiqc.py#L158)):*
> ```Python
>         self.project_name = project_obj.name
>         self.date = datetime.strptime(
>             self.project_name.split("_")[1], "%y%m%d"
> ```

does this need some kind of check first to ensure that we get a 6 digit number here so it doesn't raise a value error? i.e if someone names a project differently, this will also then ensure that the next field should be the sequencer ID for below



_Code quote:_
```Python
        self.date = datetime.strptime(
            self.project_name.split("_")[1], "%y%m%d"
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/19)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 158 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/19#-Nb-1dvdEsx7_kBG7N1W:-Nb-9xyT3AYbAD_dLb0S:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/090761defd7a06b78602b0b44180d16058642c6c/trendyqc/trend_monitoring/management/commands/_multiqc.py#L158)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this need some kind of check first to ensure that we get a 6 digit number here so it doesn't raise a value error? i.e if someone names a project differently, this will also then ensure that the next field should be the sequencer ID for below
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/19)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
