### PR TITLE
Parsing multiqc reports and config files

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Class for multiqc reports
- Config file for the assays
- Config files for the tools
- Parsing of config files

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/7)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/7)* status: 13 of 21 files reviewed, 24 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_dtwLI9CP81mH_nVCv:-N_hI5CR4sx_6Qjkl3Mz:b-1bjod2) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

note 4 me - got to here and gave up
</blockquote></details>

thanks me
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hICunENJ4nfR9AoYq:-N_hICunENJ4nfR9AoYr:bjbzqvx) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L19)):*
> ```Python
>     def parse_multiqc_report(self) -> Dict:
>         """ Parse the multiqc report for easy import
>         Output should look like:
> ```

beautiful docstring :heart: 
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hIMcW8x4glizlqLqf:-N_hIMcW8x4glizlqLqg:bqeebwb) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L42)):*
> ```Python
>         for multiqc_field, tool_metadata in self.suite_of_tools.items():
>             tool, subtool = tool_metadata
>             assert multiqc_field in raw_data, (
> ```

do we still want this assert? is this what you were talking about yesterday?
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 59 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hIeymAg7qEEAj-8Yu:-N_hIeynE3Lqcsya51hC:bpcgwij) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L59)):*
> ```Python
>                 )
> 
>                 sample_data = sample.split("_")
> ```

what format do you expect the name to be? is this to try get back to the sample name as it would be from the samplesheet? (i.e. without the lane etc?)
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 74 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hJY3A0h2Phl1DxJEN:-N_hJY3B2Gp8W7kDGINd:bov9kxy) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L74)):*
> ```Python
>                 data[sample_id].setdefault(tool, {})
> 
>                 if subtool:
> ```

what is subtool?
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 81 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hJNE79-K9h51nV7lG:-N_hJNE79-K9h51nV7lH:b-i4u7zt) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L81)):*
> ```Python
>                 # fastqc needs a new level to take into account the lane and
>                 # the read
>                 if tool == "fastqc":
> ```

can this be in the block above with the other fastqc specific part?
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hKqpUAvK0K0oHyADw:-N_hKqpUAvK0K0oHyADx:bep9bdc) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L106)):*
> ```Python
>         Args:
>             tool_data (dict): Dict containing the MultiQC data for a specific
>             tool
> ```

super minor picky point, when you have a continuation line can you indent it to make it distinct from the next input? if there's a lot it gets confusing and harder to read



_Code quote:_
```Python
tool
```
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 119 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hJpQv1khkGtiKfJ6E:-N_hJpQwC3qQru2nBRpn:bt2clkh) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L119)):*
> ```Python
>         for field, data in tool_data.items():
>             if field in tool_config:
>                 converted_data[tool_config[field]] = data
> ```

what happens if `field` is not in `tool_config`? would you expect this to happen? would it be better to use `.get()` and handle it not existing?



_Code quote:_
```Python
converted_data[tool_config[field]] = data
```
___
*[`trendyqc/trend_monitoring/management/commands/_parsing.py` line 7 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hKYKW585429r6jDuW:-N_hKYKX8fAHYvTG-tHh:b-yvf6q7) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_parsing.py#L7)):*
> ```Python
> # returns the /trendyqc/trend_monitoring/management folder
> BASE_DIR_MANAGEMENT = Path(__file__).resolve().parent.parent
> CONFIG_DIR = BASE_DIR_MANAGEMENT / "configs"
> ```

I hate that this works, it looks like you're trying to divide strings



_Code quote:_
```Python
CONFIG_DIR = BASE_DIR_MANAGEMENT / "configs"
```
___
*[`trendyqc/trend_monitoring/management/commands/_parsing.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hLQjc8Tyipuy2ejET:-N_hLQjc8Tyipuy2ejEU:bespqr3) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_parsing.py#L45)):*
> ```Python
>     assay_config = CONFIG_DIR / "assays.json"
>     data = json.loads(assay_config.read_text())
>     assert assay_name in data, (
> ```

if this is going to run automatically, should we be raising asserts or logging errors and pushing them somehow to us? if its just an assert it will stop the whole script right? or will you catch it elsewhere somehow?
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hOuOI1Atsapnt5ual:-N_hOuOI1Atsapnt5uam:b-qy3ii3) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/initial_import.py#L27)):*
> ```Python
>         )
> 
>     def handle(self, *args, **options):
> ```

doc string pls



_Code quote:_
```Python
 handle(self, *args, **options):
```
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hOYWK6PSusosYiwwc:-N_hOYWK6PSusosYiwwd:b9350u6) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/initial_import.py#L38)):*
> ```Python
>             project_ids = get_all_002_projects()
> 
>         assert project_ids is not None, "Please use -a or -p_id"
> ```

this can just be `assert project_ids`



_Code quote:_
```Python
assert project_ids is not None
```
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 52 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hOyLE4SvrLq4UWWrm:-N_hOyLE4SvrLq4UWWrn:bhrh2s2) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/initial_import.py#L52)):*
> ```Python
>         for p_id in data:
>             for report_object in data[p_id]:
>                 multiqc_report = MultiQC_report(report_object)
> ```

whats the use of this? can it just be in the above loop?



_Code quote:_
```Python
        for p_id in data:
            for report_object in data[p_id]:
                multiqc_report = MultiQC_report(report_object)
```
___
*[`trendyqc/trend_monitoring/management/configs/assays.json` line 43 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hP7CN6DGHyYPM0ME2:-N_hP7COE2w7gTFInwDE:b-xl1zvs) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/configs/assays.json#L43)):*
> ```JSON
>         "multiqc_fastqc": ["fastqc", null]
>     }
> }
> ```

you not including snp?
___
*[`trendyqc/trend_monitoring/management/configs/tool_configs/bcl2fastq.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hPBcI0O4Fo0ogTG5i:-N_hPBcI0O4Fo0ogTG5j:b-lyxa3f) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/configs/tool_configs/bcl2fastq.json#L1)):*
> ```JSON
> {
> ```

fyi there is bclconvert too, tso500 uses it but we don't currently add it to the multiqc reports yet but will do when when move away from the tso500 local app, these are its output files: https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L195
___
*[`trendyqc/trend_monitoring/management/configs/tool_configs/custom_coverage.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQP4b9ewKbnbbzdxo:-N_hQP4b9ewKbnbbzdxp:b-93j6a6) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/configs/tool_configs/custom_coverage.json#L1)):*
> ```JSON
> {
> ```

maybe not for now but at some point can you add either a short readme to the tool_confgis dir or add it to the readme what this directory is thaaaaaaaaaanks
___
*[`trendyqc/trendyqc/settings.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hPwBj4aRZD8DJVW3G:-N_hPwBk2Dy_aTL6OP-Q:b2ni78k) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c2a6652db3b8a9af491ddb2acea185c92b12f5c5/trendyqc/trendyqc/settings.py#L24)):*
> ```Python
> 
> # SECURITY WARNING: keep the secret key used in production secret!
> SECRET_KEY = 'django-insecure-u^5ofyh2%^li+5w0l86s7n*j_1hbw(-(0t)lkdk#0e#gros#ln'
> ```

lol



_Code quote:_
```Python
'django-insecure-u^5ofyh2%^li+5w0l86s7n*j_1hbw(-(0t)lkdk#0e#gros#ln'
```
___
*[`trendyqc/trendyqc/settings.py` line 31 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQ13n3qLOMvdxWjPj:-N_hQ13n3qLOMvdxWjPk:bctv26y) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trendyqc/settings.py#L31)):*
> ```Python
> 
> # SECURITY WARNING: don't run with debug turned on in production!
> DEBUG = True
> ```

can this be moved to the config? 



_Code quote:_
```Python
DEBUG = True
```
___
*[`trendyqc/trendyqc/settings.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQJo-E_rsbelHW0lL:-N_hQJo-E_rsbelHW0lM:b-6ubr3l) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trendyqc/settings.py#L36)):*
> ```Python
>     'testserver',
>     'localhost'
> ]
> ```

so config or env



_Code quote:_
```Python
ALLOWED_HOSTS = [
    'testserver',
    'localhost'
]
```
___
*[`trendyqc/trendyqc/settings.py` line 94 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQFtI8Y9mkGJk77Rz:-N_hQFtI8Y9mkGJk77S-:bvd865) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trendyqc/settings.py#L94)):*
> ```Python
>         'PORT': '5432',
>     }
> }
> ```

config time pls



_Code quote:_
```Python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'qc_trends_db',
        'USER': 'qc_trends_db_user',
        'PASSWORD': 'qc_trends_db_password',
        'HOST': 'qc_trends_db',
        'PORT': '5432',
    }
}
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/7)* status: 13 of 22 files reviewed, 24 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py` line 20 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_drSZSCuEH3gN4MH7T:-N_hV9xf-TvBoYwj7X7E:b-lgjxys) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py#L20)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be logged? is the not logging in handled when the function is called?
</blockquote></details>

this will be implemented for v1 but probably in a separate PR dedicated to logging
___
*[`trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_drxsd67tNe4UeSQD2:-N_hWNun0zvFcTDMwxzC:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this is a list of DXFile objects, think its useful to define this instead of thinking its just a list of ID strings
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_drdBF5nFPtTCzIQ03:-N_hWOZB1hgXT4BluxBg:brei1ja) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py#L41)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

any reason to create a new list instead of list a list comp to filter down the current one something like this:
```
return [dxpy.DXFile(file["id"], file["project"]) for file in files]
```

if you do want to return dxpy object handles, you might want the following arg:
-   **return\_handler** (_boolean_) – If True, yields results as dxpy object handlers (otherwise, yields each result as a dict with keys “id” and “project”)

http://autodoc.dnanexus.com/bindings/python/current/dxpy_search.html?highlight=find%20project#dxpy.bindings.search.find_projects
</blockquote></details>

Very helpful, thanks. Done.
___
*[`trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py` line 55 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_ds82b8bX-Lv_Rn15-:-N_hWr6EBeosUoBIovvB:b6xgw9n) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py#L55)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be more generic in case of not wanting to look at 002_ prefix projects? (i.e. sharing it with others)
</blockquote></details>

I do have a way to specify which projects the user wants to look in.
I was thinking that this 002 function would be used for populating the database the first time around
___
*[`trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_dsFuc-Z6YUHudEdyB:-N_hWnLkDMZJ4LR9iI7M:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_dnanexus_utils.py#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could be a list comp again with `return [project['id'] for project in projects]
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_dtwLI9CP81mH_nVCv:-N_hXNVw5DHxBPqRKiX_:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

thanks me
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hICunENJ4nfR9AoYq:-N_hXORhCbymLHUDaKpk:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L19)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

beautiful docstring :heart: 
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hIMcW8x4glizlqLqf:-N_hXtSeDNOqXWW3gB9Q:b-dswsl3) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L42)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do we still want this assert? is this what you were talking about yesterday?
</blockquote></details>

No this one is fine. It checks whether a field from the config file i.e. `multiqc_bcl2fastq_bysample` is present in the multiqc data.
But i do agree that it can be confusing
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 59 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hIeymAg7qEEAj-8Yu:-N_hYQxsE0sV4BYpxovn:b-jzxa2g) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L59)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what format do you expect the name to be? is this to try get back to the sample name as it would be from the samplesheet? (i.e. without the lane etc?)
</blockquote></details>

yes

```
# For a random myeloid run
# for HSmetrics
122667352-23114Z0092-23NGSHO1-8128-M-96527893

# for insertsize
122667352-23114Z0092-23NGSHO1-8128-M-96527893_FR

# for fastqc
122667352-23114Z0092-23NGSHO1-8128-M-96527893_S14_L001_R1
```

I think the assertion on the number of fields should catch any weird errors in the sample naming
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 74 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hJY3A0h2Phl1DxJEN:-N_h_PIQCNiTZCTAuhR5:b-a2sipt) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L74)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is subtool?
</blockquote></details>

i put a comment in line 41. Done.
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 81 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hJNE79-K9h51nV7lG:-N_h_fvl95iw5PKKQsn5:byw3ohu) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L81)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be in the block above with the other fastqc specific part?
</blockquote></details>

i don't think so i need to setup the tool key first to setup the dict
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hKqpUAvK0K0oHyADw:-N_h_xm-1YhfOs2cG76A:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L106)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

super minor picky point, when you have a continuation line can you indent it to make it distinct from the next input? if there's a lot it gets confusing and harder to read
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_multiqc.py` line 119 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hJpQv1khkGtiKfJ6E:-N_hbrg09HaZMtcPhy5H:b-giccov) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_multiqc.py#L119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what happens if `field` is not in `tool_config`? would you expect this to happen? would it be better to use `.get()` and handle it not existing?
</blockquote></details>

i don't think i would expect those to change since they are tied to the tools and they shouldn't change often at least
___
*[`trendyqc/trend_monitoring/management/commands/_parsing.py` line 7 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hKYKW585429r6jDuW:-N_hc2Y49B18vy3KwoIv:b8m4d10) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_parsing.py#L7)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I hate that this works, it looks like you're trying to divide strings
</blockquote></details>

nah it's great
___
*[`trendyqc/trend_monitoring/management/commands/_parsing.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hLQjc8Tyipuy2ejET:-N_hc5i6EGJei_hY7Zzp:b-120hsh) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/_parsing.py#L45)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if this is going to run automatically, should we be raising asserts or logging errors and pushing them somehow to us? if its just an assert it will stop the whole script right? or will you catch it elsewhere somehow?
</blockquote></details>

I'll add logging later
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hOuOI1Atsapnt5ual:-N_hcX3d9qfY-5IP17bc:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/initial_import.py#L27)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

doc string pls
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hOYWK6PSusosYiwwc:-N_hcb6HEqSkaDQyYEU9:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/initial_import.py#L38)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can just be `assert project_ids`
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/initial_import.py` line 52 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hOyLE4SvrLq4UWWrm:-N_hfCwmAzxJlcCA0ALq:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/commands/initial_import.py#L52)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

whats the use of this? can it just be in the above loop?
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/configs/assays.json` line 43 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hP7CN6DGHyYPM0ME2:-N_hfDqy5FEZ-TsC5FH3:bi78ry9) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/configs/assays.json#L43)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you not including snp?
</blockquote></details>

i forgot about snppppppppppppppp
___
*[`trendyqc/trend_monitoring/management/configs/tool_configs/bcl2fastq.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hPBcI0O4Fo0ogTG5i:-N_hi5fv6FfrrXLwF2_7:bn0ue6d) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/configs/tool_configs/bcl2fastq.json#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

fyi there is bclconvert too, tso500 uses it but we don't currently add it to the multiqc reports yet but will do when when move away from the tso500 local app, these are its output files: https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L195
</blockquote></details>

i don't wanna write a new config file
___
*[`trendyqc/trend_monitoring/management/configs/tool_configs/custom_coverage.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQP4b9ewKbnbbzdxo:-N_hiDEy-jAZTA9a_LRq:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trend_monitoring/management/configs/tool_configs/custom_coverage.json#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

maybe not for now but at some point can you add either a short readme to the tool_confgis dir or add it to the readme what this directory is thaaaaaaaaaanks
</blockquote></details>

Done.
___
*[`trendyqc/trendyqc/settings.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hPwBj4aRZD8DJVW3G:-N_hiEAmEfRr5Y89gJhT:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c2a6652db3b8a9af491ddb2acea185c92b12f5c5/trendyqc/trendyqc/settings.py#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

lol
</blockquote></details>

Done.
___
*[`trendyqc/trendyqc/settings.py` line 31 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQ13n3qLOMvdxWjPj:-N_hiEpY-HzxPgY1IKWH:b-d7bhn0) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trendyqc/settings.py#L31)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be moved to the config? 
</blockquote></details>

will do
___
*[`trendyqc/trendyqc/settings.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQJo-E_rsbelHW0lL:-N_hiG6m8TueHPaRWhBX:b-d7bhn0) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trendyqc/settings.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

so config or env
</blockquote></details>

will do
___
*[`trendyqc/trendyqc/settings.py` line 94 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/7#-N_hQFtI8Y9mkGJk77Rz:-N_hiHXQDyMguIdW9Iat:b-d7bhn0) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fba646a4f238c10f72d379dc52b2ced2fff5910d/trendyqc/trendyqc/settings.py#L94)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

config time pls
</blockquote></details>

will do

**Review by jethror1 — APPROVED** [review]
> Reviewed 4 of 21 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/7)* status: all files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/7)* status: all files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

**Pull request merged**
