### PR TITLE
In 571 unittesting verify bam

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/81)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/81)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/tests/custom_tests.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/81#-NwEk1l7-3RAtwIfLyFA:-NwEk1l7-3RAtwIfLyFB:b-ujfsju) ([raw file](https://github.com/eastgenomics/trendyQC/blob/24ed3228dc62a522c671d26767eec7e5848971da/trendyqc/trend_monitoring/tests/custom_tests.py#L48)):*
> ```Python
>             else:
>                 if value1 == "NA":
>                     if value2 is not None:
> ```

confused by what you're trying to achieve here andf how this means they're not equal?



_Code quote:_
```Python
                if value1 == "NA":
                    if value2 is not None:
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/81)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/tests/custom_tests.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/81#-NwEk1l7-3RAtwIfLyFA:-NwF1MAv6EiHFvxR8rzM:burmayz) ([raw file](https://github.com/eastgenomics/trendyQC/blob/24ed3228dc62a522c671d26767eec7e5848971da/trendyqc/trend_monitoring/tests/custom_tests.py#L48)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

confused by what you're trying to achieve here andf how this means they're not equal?
</blockquote></details>

i realised that this was dumb, does my new changes make more sense?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/81)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/tests/custom_tests.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/81#-NwEk1l7-3RAtwIfLyFA:-NwFMb5c42HgJQg2efA-:b-o19ise) ([raw file](https://github.com/eastgenomics/trendyQC/blob/24ed3228dc62a522c671d26767eec7e5848971da/trendyqc/trend_monitoring/tests/custom_tests.py#L48)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i realised that this was dumb, does my new changes make more sense?
</blockquote></details>

makes more sense now, could it be refactored to just:
```
try:
    
                    if float(value1) != float(value2):
                        raise AssertionError(
                            f"{value1} is not equal to {value2}"
                        )
                except Exception:
                    raise AssertionError(
                        f"{value1} is not kinda equal to {value2}"
                    )

```

that spacing has gone weird but you get the idea

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/81)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/tests/custom_tests.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/81#-NwEk1l7-3RAtwIfLyFA:-NwJUofeE5G295M2gFSp:b-l0cib8) ([raw file](https://github.com/eastgenomics/trendyQC/blob/24ed3228dc62a522c671d26767eec7e5848971da/trendyqc/trend_monitoring/tests/custom_tests.py#L48)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

makes more sense now, could it be refactored to just:
```
try:
    
                    if float(value1) != float(value2):
                        raise AssertionError(
                            f"{value1} is not equal to {value2}"
                        )
                except Exception:
                    raise AssertionError(
                        f"{value1} is not kinda equal to {value2}"
                    )

```

that spacing has gone weird but you get the idea
</blockquote></details>

i got errors when comparing "NA" and None, i think there would need to be an additional condition to make sure that "", "NA" and None are understood to be equivalent to one another

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
