### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Functional filters:
- filter creation
- filter deletion
- filter table

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/31)

### CODE REVIEW

**Review by jethror1 — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/31)* status: 10 of 12 files reviewed, all discussions resolved

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/31)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/views.py` line 137 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/31#-Nj85WlVBxLQdDNXwL4o:-Nj85WlVBxLQdDNXwL4p:b-1j7pwe) ([raw file](https://github.com/eastgenomics/trendyQC/blob/542d43aaa389c65f81e3b462c99ae7c6cb7375e0/trendyqc/trend_monitoring/views.py#L137)):*
> ```Python
>         table_counter = count()
>         filter_table.prefix = filter_table.prefix or self.table_prefix.format(next(table_counter))
>         RequestConfig(self.request, paginate=self.get_table_pagination(filter_table)).configure(filter_table)
> ```

these not a bit long?



_Code quote:_
```Python
        filter_table.prefix = filter_table.prefix or self.table_prefix.format(next(table_counter))
        RequestConfig(self.request, paginate=self.get_table_pagination(filter_table)).configure(filter_table)
```
___
*[`trendyqc/trend_monitoring/backend_utils/filtering.py` line 31 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/31#-Nj84w3YCHokLDJp799o:-Nj84w3YCHokLDJp799p:bdpxy5g) ([raw file](https://github.com/eastgenomics/trendyQC/blob/542d43aaa389c65f81e3b462c99ae7c6cb7375e0/trendyqc/trend_monitoring/backend_utils/filtering.py#L31)):*
are these parentheses not redundant? a return automatically returns items as a tuple:
```
>>> def test():
...     return 1, 2
... 
>>> a = test()
>>> a
(1, 2)
>>> 
>>> def test():
...     return (1, 2)
... 
>>> a = test()
>>> a
(1, 2)

```



_Code quote:_
```Python
return (f"Filter {filter_name} already exists", messages.ERROR)
```
___
*[`trendyqc/trend_monitoring/backend_utils/filtering.py` line 59 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/31#-Nj84Vq8Ed81xrXKciIg:-Nj84Vq9BMSYPIIpMrvO:b-ngaymi) ([raw file](https://github.com/eastgenomics/trendyQC/blob/542d43aaa389c65f81e3b462c99ae7c6cb7375e0/trendyqc/trend_monitoring/backend_utils/filtering.py#L59)):*
> ```Python
>         return obj.isoformat()
> 
>     raise TypeError ("Type %s not serializable" % type(obj))
> ```

any reason to not use an f string here? also space after `TypeError`



_Code quote:_
```Python
raise TypeError ("Type %s not serializable" % type(obj))
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/31)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/views.py` line 137 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/31#-Nj85WlVBxLQdDNXwL4o:-Nj87J-T5uUyOTET9qy5:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/542d43aaa389c65f81e3b462c99ae7c6cb7375e0/trendyqc/trend_monitoring/views.py#L137)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

these not a bit long?
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/backend_utils/filtering.py` line 31 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/31#-Nj84w3YCHokLDJp799o:-Nj87XmZ6PkOR-HHZOyO:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/542d43aaa389c65f81e3b462c99ae7c6cb7375e0/trendyqc/trend_monitoring/backend_utils/filtering.py#L31)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are these parentheses not redundant? a return automatically returns items as a tuple:
```
>>> def test():
...     return 1, 2
... 
>>> a = test()
>>> a
(1, 2)
>>> 
>>> def test():
...     return (1, 2)
... 
>>> a = test()
>>> a
(1, 2)

```
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/backend_utils/filtering.py` line 59 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/31#-Nj84Vq8Ed81xrXKciIg:-Nj87Yn8BHaRDnei3neQ:b-ba9hrg) ([raw file](https://github.com/eastgenomics/trendyQC/blob/542d43aaa389c65f81e3b462c99ae7c6cb7375e0/trendyqc/trend_monitoring/backend_utils/filtering.py#L59)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

any reason to not use an f string here? also space after `TypeError`
</blockquote></details>

I copy pasted stuff there :D
Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
