### PR TITLE
In 506 unittesting happy

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/74)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/74)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/tests/custom_tests.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/74#-Nw3zx-83iOR5YZAE9U4:-Nw3zx-83iOR5YZAE9U5:b-22vo1y) ([raw file](https://github.com/eastgenomics/trendyQC/blob/2b5cf093d5dc5eaa70b2ce5bcc98a416c3f8a295/trendyqc/trend_monitoring/tests/custom_tests.py#L41)):*
be careful with equality comparison of floats due to th eprecision with which they're stored (not sure if its an issue here depending on where this is used), `math.isclose()` is good for this and lets you set precision, for example:

```
>>> 0.1 + 0.2 == 0.3
False
>>> import math
>>> math.isclose((0.1 + 0.2), 0.3)
True
```



_Code quote:_
```Python
if float(value1) != float(value2):
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/74)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/tests/custom_tests.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/74#-Nw3zx-83iOR5YZAE9U4:-Nw41x-u0uWi_Req8O6V:b-vxrmb8) ([raw file](https://github.com/eastgenomics/trendyQC/blob/2b5cf093d5dc5eaa70b2ce5bcc98a416c3f8a295/trendyqc/trend_monitoring/tests/custom_tests.py#L41)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

be careful with equality comparison of floats due to th eprecision with which they're stored (not sure if its an issue here depending on where this is used), `math.isclose()` is good for this and lets you set precision, for example:

```
>>> 0.1 + 0.2 == 0.3
False
>>> import math
>>> math.isclose((0.1 + 0.2), 0.3)
True
```
</blockquote></details>

hum interesting, i think it should be fine since I convert strings into float and then compare them.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/74)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/74)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
