### PR TITLE
In 743 add last x days filtering option

### LINKED ISSUE #119: Saved filter date range
I'd like to be able to set a filter to show the last x days rather than a fixed date range. This would make the filter more reusable

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Add a `days back` filtering option
    - will get data for the last x `days back` option selected
    - should be dynamic i.e. if saved in a filter and that filter applies the days back option for when the filter is used. Resolves #119 
- Display the data used for filtering the plot data in a more human readable way
- Display the form data in the filter table in a more human readable way

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/123)

### CODE REVIEW

**Review by PolarisAstrum-NHS — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/123)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/forms.py` line 102 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/123#-O4oDedY1YGtJatacYpZ:-O4oDedY1YGtJatacYp_:b-6cyll1) ([raw file](https://github.com/eastgenomics/trendyQC/blob/39b5a211c19c88042ca133a2ed37102918a3692d/trendyqc/trend_monitoring/forms.py#L102)):*
> ```Python
> 
>         if cleaned_data.get("days_back", None):
>             cleaned_data["days_back"] = cleaned_data.get("days_back")
> ```

What is this line performing?  It looks like if "days_back" contains a value, it sets this value to itself

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/123)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @PolarisAstrum-NHS)

___
*[`trendyqc/trend_monitoring/forms.py` line 102 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/123#-O4oDedY1YGtJatacYpZ:-O4oLrrD9xUEwGDhvGRO:b-h6d31z) ([raw file](https://github.com/eastgenomics/trendyQC/blob/39b5a211c19c88042ca133a2ed37102918a3692d/trendyqc/trend_monitoring/forms.py#L102)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

What is this line performing?  It looks like if "days_back" contains a value, it sets this value to itself
</blockquote></details>

my mistake, Done.

**Review by PolarisAstrum-NHS — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/123#-:-O4oPslk7uFCt6pHN7Zt:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by PolarisAstrum-NHS — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/123)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
