### PR TITLE
Use OOP for tools as well

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Tools are now objects
- Should help with the import by storing parents and children (don't know how yet)
- Remove some code from parsing script
- Remove some code from MultiQC script

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/12)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/12)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_parsing.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/12#-NaBWfpd9Sl_nZFlG1_1:-NaBWfpd9Sl_nZFlG1_2:ba0za5u) ([raw file](https://github.com/eastgenomics/trendyQC/blob/8db92cd35a46b31ed0b04934c30856d4776d39fb/trendyqc/trend_monitoring/management/commands/_parsing.py#L5)):*
> ```Python
> 
> 
> def load_assay_config(assay_name: str, config_dir) -> Dict:
> ```

new input missing type and arg in docstring



_Code quote:_
```Python
config_dir
```
___
*[`trendyqc/trend_monitoring/management/commands/_tool.py` line 68 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/12#-NaBXD_78XGR1aCRuGVS:-NaBXD_78XGR1aCRuGVT:buey86p) ([raw file](https://github.com/eastgenomics/trendyQC/blob/8db92cd35a46b31ed0b04934c30856d4776d39fb/trendyqc/trend_monitoring/management/commands/_tool.py#L68)):*
> ```Python
>         for field, data in multiqc_data.items():
>             # check if the multiqc field exists in our config mapping file
>             if field in self.fields:
> ```

if it isn't present do we want to log or do something with it?



_Code quote:_
```Python
f field in self.fields:
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/12)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/_parsing.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/12#-NaBWfpd9Sl_nZFlG1_1:-NaBYOcO8aF1AKNWzzgI:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/8db92cd35a46b31ed0b04934c30856d4776d39fb/trendyqc/trend_monitoring/management/commands/_parsing.py#L5)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

new input missing type and arg in docstring
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/management/commands/_tool.py` line 68 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/12#-NaBXD_78XGR1aCRuGVS:-NaBYRhJBSrikT44BkPM:bkrmbhk) ([raw file](https://github.com/eastgenomics/trendyQC/blob/8db92cd35a46b31ed0b04934c30856d4776d39fb/trendyqc/trend_monitoring/management/commands/_tool.py#L68)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if it isn't present do we want to log or do something with it?
</blockquote></details>

i'm not sure yet what to do with that, but yeah probably

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/12)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/_tool.py` line 68 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/12#-NaBXD_78XGR1aCRuGVS:-NaBZVCb5RdKJ0b951Ih:b-948eas) ([raw file](https://github.com/eastgenomics/trendyQC/blob/8db92cd35a46b31ed0b04934c30856d4776d39fb/trendyqc/trend_monitoring/management/commands/_tool.py#L68)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'm not sure yet what to do with that, but yeah probably
</blockquote></details>

wanna slap in a TODO for future you?

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/12)* status: 2 of 3 files reviewed, all discussions resolved

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
