### PR TITLE
Unittesting views part 1

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Have actual tool names for the metric scrolling menu
    - JSON to configure the name to display
    - additional cleaning step for posting data
- Unittesting views:
     - Dashboard:
          - GET | correct context data
          - POST | plot using scrolling menus
          - POST | plot using filter
          - POST | delete filter
          - POST | save filter
      - Plot:
          - GET | correct form to reach final render function
          - GET | empty form

```
root@29cb345eed2c:/app# python trendyqc/manage.py test trend_monitoring.tests
Found 37 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.....................................
----------------------------------------------------------------------
Ran 37 tests in 49.630s

OK
Destroying test database for alias 'default'...
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/91)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/91)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/views.py` line 107 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-Nyyj-zp2FqVe6oWdxGV:-Nyyj-zp2FqVe6oWdxGW:bw1bgdg) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/views.py#L107)):*
> ```Python
> 
>         for model_name, model in module_dict.items():
>             if model_name in DISPLAY_DATA_JSON:
> ```

do you need to handle here if you haven't got the model in your config?



_Code quote:_
```Python
if model_name in DISPLAY_DATA_JSON:
```
___
*[`trendyqc/trend_monitoring/management/configs/displaying_data.json` line 13 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-NyyjOts7eOQFDHjv7oT:-NyyjOtt6nV4N48RNH2b:b-2t9dka) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/management/configs/displaying_data.json#L13)):*
> ```JSON
>     "PCR_metrics": "Picard - PCR metrics",
>     "Duplication_metrics": "Picard - Duplication metrics",
> ```

why space?
___
*[`trendyqc/trend_monitoring/tests/test_views.py` line 287 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-NyyllRW6bHFTwMWzn7T:-NyyllRX4ZBc5FvBluvg:b-732xk1) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/tests/test_views.py#L287)):*
> ```Python
>         with self.subTest("Context data content test"):
>             # for some reason i get 2 identical elements in the context data so
>             # I need to loop to check one if the context data content
> ```

what does the context data here look like? are both identical where there's duplicates?



_Code quote:_
```Python
            # for some reason i get 2 identical elements in the context data so
            # I need to loop to check one if the context data content
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/91)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/views.py` line 107 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-Nyyj-zp2FqVe6oWdxGV:-NyynZTE27IeVs3_HqSM:b-hic7wj) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/views.py#L107)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you need to handle here if you haven't got the model in your config?
</blockquote></details>

i do because i have some models that are not relevant for the plotting i.e. link tables that are still getting looped over
___
*[`trendyqc/trend_monitoring/management/configs/displaying_data.json` line 13 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-NyyjOts7eOQFDHjv7oT:-NyyoUKo7HACjeQ-Rp_4:bhs1srn) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/management/configs/displaying_data.json#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why space?
</blockquote></details>

different tool types i.e. bam, fastq, vcf
___
*[`trendyqc/trend_monitoring/tests/test_views.py` line 287 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-NyyllRW6bHFTwMWzn7T:-O-eRfmA1vi5y2nfeZHE:b-gskjtv) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/tests/test_views.py#L287)):*
I wonder if this might be why i get 2 context data from https://docs.djangoproject.com/en/5.0/topics/testing/tools/#django.test.Response.context :
> If the rendered page used multiple templates, then `context` will be a list of `Context` objects, in the order in which they were rendered.
Since the plot.html template is a block used in base.html, does Django think that it needs to return 2 context data objects?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/91)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 517 at r4](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-O-ehh3j37Z3ancE8q6v:-O-enbFC9R-nuIhyTz5L:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/220591933dab4298727c5d24606138b4eeacf1b2/trendyqc/trend_monitoring/backend_utils/plot.py#L517)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why here do you only call `item()` if its a `float64`?
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/tests/test_views.py` line 287 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-NyyllRW6bHFTwMWzn7T:-O-enc5v35-LMGruBfEg:b7zrh6v) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/tests/test_views.py#L287)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

have you decided this is not an issue? is it just observed in testing?
</blockquote></details>

observed in prod as well:



I think it confirms my suspicion as well

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/91)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/tests/test_views.py` line 287 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/91#-NyyllRW6bHFTwMWzn7T:-O-fljco3NvIqtrn7JCo:bom6lyn) ([raw file](https://github.com/eastgenomics/trendyQC/blob/fd7aaff1fe7bcc67e6da4f65f8668b6214da3184/trendyqc/trend_monitoring/tests/test_views.py#L287)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'm not sure how to handle this.
my gut feeling tells me i'm doing something wrong in the handling of requests/context data but i have no idea why
</blockquote></details>

can you step through the code before returning the request to find where its duplicated?

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/91)* status: 13 of 14 files reviewed, all discussions resolved

**Pull request merged**
