### PR TITLE
Various fixes/improvements

### LINKED ISSUE #41: banner messages don't fade out
image

### LINKED ISSUE #43: restrict saving filters to only logged in users

### LINKED ISSUE #44: add a confirmation dialogue when deleting a saved filter

### LINKED ISSUE #45: add in 'created by' against each filter
also might be nice to be able to easily filter by current users saved filters if there's a lot

### LINKED ISSUE #46: fix width of selectors
currently y axis selector opens the menu off the side of the screen, would be better to reduce the width of the subset selection and x axis as they look to set to 40%, dropping this to even 33% each of the parent div should work better
image

### LINKED ISSUE #47: header alignment
the 'trend monitoring' text looks odd and not aligned to anything, I think it would look better aligned to the left next to TrendyQC and remove the hyperlink from it or just removed
image

### LINKED ISSUE #51: nicer rendering of drop down
drop down might be better wider for readability

image

currently is 30%, set to 60% is nicer (although it causes the other buttons to shift, would be better if it floated the drop down over them)

image

### LINKED ISSUE #53: saving filter changes the button name
saving an invalid filter raised a ValueError like when trying to plot, but going back weirdly adds the filter named over the 'Save filter' button, might have some reused variable there

image

### LINKED ISSUE #54: add metric being plotted to Y axis
i.e. GC pct here

image

### LINKED ISSUE #55: Filter content being long is an issue
You don't see the use/delete buttons.

image

### PR DESCRIPTION
**Pull request by Yu-jinKim**
# Changes

- New version of JQuery + non slim version
- Fixes #41 
- Fixes #43 
- Fixes #44 
- Fixes #45 
- Fixes #46 
- Fixes #47 
- Fixes #51 
- Fixes #53 
- Fixes #54 
- Fixes #55
- Fixes in the filter table and the recap in the Plot page for the displaying of the dates

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/57)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/57)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/tables.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/57#-NlTdrtg8TUl6B1Ke4zv:-NlTdrthB16IbUfbfP7M:b32x0h) ([raw file](https://github.com/eastgenomics/trendyQC/blob/b38cb8dfe9aa91e58f71f7d695a5689c0260af34/trendyqc/trend_monitoring/tables.py#L57)):*
> ```Python
>             for value in values:
>                 data += f"<li>{value}</li>"
>             
> ```

ws

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/57)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/tables.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/57#-NlTdrtg8TUl6B1Ke4zv:-NlTi8yj7yhpnCxTJYyi:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/b38cb8dfe9aa91e58f71f7d695a5689c0260af34/trendyqc/trend_monitoring/tables.py#L57)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/57)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/57)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
