### PR TITLE
In 644 fix plotting following lane changes

### LINKED ISSUE #92: Improve plotting with multiple lanes
Following dev and design meeting 31/05/2024:
- Offset boxplots for 1st and 2nd lane
- Change color of edges
- Grid lines
- Add 2nd y axis
- Customise hover text to not display run name

### LINKED ISSUE #94: Create groups when plotting multiple assays or multiple sequencers
Plotting multiple sequencers/assays mixes every run in the xaxis.
Grouping them could be a good solution.

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Closes #92 
Closes #94 

### Backend
- `get_data_for_plotting`:
    - make the gathering of data dynamic i.e. if multiple lanes, check absence of data for each lane
- `get_metric_filter`:
    - build the filter as soon as `read_data` aka fastqc or `base_distribution` is detected for lane purposes
- `format_data_for_plotly_js`:
    - remove median trace
    - create boxes for the first and second lanes if needed
    - setup traces to be further divided by month
- *NEW* `create_trace`:
    - allows fine tuning of trace creation via kwargs
- *NEW* `get_date_from_project_name`:
    - given the project name extract the date to format it for the xaxis
- *NEW* `calculate_mean_across_columns`:
    - allows computation of mean across columns given a pandas series (used in conjunction of `apply`)
### Models
- fix error field names for `base_distribution`
### Template
- `plot`:
    - add dividers to xaxis to display month and year
    - show lines for x/y axes
    - boxmode thingy for no overlap when having multiple boxes for one tick

image

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
are you intentionally not angling the x axis labels?

does this include changes for making the hover text nicerer?

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-:-Nzi3ctQ7zvUiEfZ0tlK:b-448y8e)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 563 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-Nzi2Ss51HZMo7kS6G0n:-Nzi2Ss51HZMo7kS6G0o:b-d76or2) ([raw file](https://github.com/eastgenomics/trendyQC/blob/3c5c9e72e67fc3d2410e994ec8612ff8be346aa7/trendyqc/trend_monitoring/backend_utils/plot.py#L563)):*
are you intentionally excluding null values here from your calculation vs treating them as zero?

also, for calculating the mean across columns / rows, why not use the built in `mean()`?

```
>>> df
         a  b  c  d  mean
0  string1  1  2  3   2.0
1  string2  4  5  6   5.0

>>> df[['b', 'c', 'd']].mean(axis=1)
0    2.0
1    5.0
dtype: float64

```

I feel like this is going to be fairly slow since its loops in loops in loops



_Code quote:_
```Python
    for column in columns:
        if row.iloc[column]:
            value += row[column]
            denominator += 1
```

**Comment by Yu-jinKim** [comment]
Coloring by group (assay sequencer id)
image

**Comment by Yu-jinKim** [comment]
Coloring by sequencer id
image

**Comment by Yu-jinKim** [comment]
Grouping by assay
image

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 395 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-O-a-9Q1AVpQbDP85usO:-O-a-9Q1AVpQbDP85usP:b-y4dkp8) ([raw file](https://github.com/eastgenomics/trendyQC/blob/06a7d85f0a00d250267ce3b71dff651fc553e6bf/trendyqc/trend_monitoring/backend_utils/plot.py#L395)):*
> ```Python
>         # too many groups are available
>         if not colors and i != len(groups) - 1:
>             raise AssertionError("No more colors possible")
> ```

is this a function called from the front end? do you want to raise an assertion error?



_Code quote:_
```Python
raise AssertionError("No more colors possible")
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 563 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-Nzi2Ss51HZMo7kS6G0n:-O-aMqU78hKCd636-Pdl:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/3c5c9e72e67fc3d2410e994ec8612ff8be346aa7/trendyqc/trend_monitoring/backend_utils/plot.py#L563)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are you intentionally excluding null values here from your calculation vs treating them as zero?

also, for calculating the mean across columns / rows, why not use the built in `mean()`?

```
>>> df
         a  b  c  d  mean
0  string1  1  2  3   2.0
1  string2  4  5  6   5.0

>>> df[['b', 'c', 'd']].mean(axis=1)
0    2.0
1    5.0
dtype: float64

```

I feel like this is going to be fairly slow since its loops in loops in loops
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 395 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-O-a-9Q1AVpQbDP85usO:-O-aMs1-5HPt6k_UP8X_:b-4wuwiw) ([raw file](https://github.com/eastgenomics/trendyQC/blob/06a7d85f0a00d250267ce3b71dff651fc553e6bf/trendyqc/trend_monitoring/backend_utils/plot.py#L395)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this a function called from the front end? do you want to raise an assertion error?
</blockquote></details>

not sure what would be the best way to handle this actually.
i believe this would raise a 404 ? but a message explaining the issue doesn't necessarily help the user it i.e. selecting less parameters to create less unique groups of assay/sequencer ids. Especially if they want to see that data, unless i add more colors but the amount of parameters could grow i.e. new sequencers new assays

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 395 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-O-a-9Q1AVpQbDP85usO:-O-aRdt48OTRUexb99gp:b-yjkj8c) ([raw file](https://github.com/eastgenomics/trendyQC/blob/06a7d85f0a00d250267ce3b71dff651fc553e6bf/trendyqc/trend_monitoring/backend_utils/plot.py#L395)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not sure what would be the best way to handle this actually.
i believe this would raise a 404 ? but a message explaining the issue doesn't necessarily help the user it i.e. selecting less parameters to create less unique groups of assay/sequencer ids. Especially if they want to see that data, unless i add more colors but the amount of parameters could grow i.e. new sequencers new assays
</blockquote></details>

I think having it actually return the page with some level of more helpful "internal error occurred" would be nicer, then you can add some kind of useful error ID that can be in the logs for making debugging easier. Having the site just break with a 404 is unhelpful in terms of trying to figure out why it broke

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/backend_utils/plot.py` line 395 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/93#-O-a-9Q1AVpQbDP85usO:-O-aoulFDMAxB_sbO1qN:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/06a7d85f0a00d250267ce3b71dff651fc553e6bf/trendyqc/trend_monitoring/backend_utils/plot.py#L395)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think having it actually return the page with some level of more helpful "internal error occurred" would be nicer, then you can add some kind of useful error ID that can be in the logs for making debugging easier. Having the site just break with a 404 is unhelpful in terms of trying to figure out why it broke
</blockquote></details>

Done.

**Comment by Yu-jinKim** [comment]
Couldn't actually trigger the error message because i can cover all possible groups with the amount of colors i have right now.
Will check when i do the unittesting

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/93)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
