### PR TITLE
In 588 fix import of multiple lane for tools that separate their data by lane

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Fix issue where lane assignment could be other than L001 + L002
    - Introduce system to assign lane number to a `1st` or `2nd` lane number
    - Rename fields in Picard to match new system
- Make functions for setting up and import reports, units
- Rewrite the init for MultiQC reports
- New fields for Custom coverage
- Adjust tests to match changes
```
python trendyqc/manage.py test trend_monitoring.tests
Found 30 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..............................
----------------------------------------------------------------------
Ran 30 tests in 65.637s

OK
Destroying test database for alias 'default'...
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/utils/_multiqc.py` line 490 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL5UwdEMlQALo7gbxp:-NyL5UwdEMlQALo7gbxq:b-broopb) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/management/commands/utils/_multiqc.py#L490)):*
> ```Python
> 
>         instance_type_tables = {}
>         lane_dict = {0: "1st_lane", 1: "2nd_lane"}
> ```

why are you limiting this to just 2 lanes? afaik on a NoveSeq flowcell there can be up to 4 lanes (although this might just be on an S4 flowcell)



_Code quote:_
```Python
lane_dict = {0: "1st_lane", 1: "2nd_lane"}
```
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL6PnX6jjdKOoDEH51:-NyL6PnX6jjdKOoDEH52:b-i13cfn) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/tests/test_multiqc.py#L511)):*
> ```Python
>                         # base content but not the right lane
>                         if not db_data:
>                             continue
> ```

do we just want to silently continue here?



_Code quote:_
```Python
                        if not db_data:
                            continue
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/utils/_multiqc.py` line 490 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL5UwdEMlQALo7gbxp:-NyLF-yCCIEdS2gbfJDz:bov8zzh) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/management/commands/utils/_multiqc.py#L490)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why are you limiting this to just 2 lanes? afaik on a NoveSeq flowcell there can be up to 4 lanes (although this might just be on an S4 flowcell)
</blockquote></details>

as in you can have L001_R1 | L001_R2 | L002_R1 | L002_R2 | L003_R1 | L003_R2 | L004_R1 | L004_R1 ?
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL6PnX6jjdKOoDEH51:-NyLFg-O85imb9aUnsli:b-xhxryf) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/tests/test_multiqc.py#L511)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do we just want to silently continue here?
</blockquote></details>

i think so? I want to continue to find the correct lane

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/utils/_multiqc.py` line 490 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL5UwdEMlQALo7gbxp:-NyLSrpJ9SL9m-rSCBk3:b-pb9bue) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/management/commands/utils/_multiqc.py#L490)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

as in you can have L001_R1 | L001_R2 | L002_R1 | L002_R2 | L003_R1 | L003_R2 | L004_R1 | L004_R1 ?
</blockquote></details>

indeed

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL6PnX6jjdKOoDEH51:-NyLSrBPCx0zZZXzlWhr:b671t9c) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/tests/test_multiqc.py#L511)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

and what if you don't find any? does it need catching?
</blockquote></details>

there's an assert at line 520 that should catch empty stuff

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/utils/_multiqc.py` line 490 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL5UwdEMlQALo7gbxp:-NyLT6Wf7WD5t9yQZYIV:b-yfq91f) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/management/commands/utils/_multiqc.py#L490)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

indeed
</blockquote></details>

do we have those cases yet?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/management/commands/utils/_multiqc.py` line 490 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL5UwdEMlQALo7gbxp:-NyLYhb3A7Firqbwdrg5:bb189k4) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/management/commands/utils/_multiqc.py#L490)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do we have those cases yet?
</blockquote></details>

I don't think we've got to S4 yet routinely for WES, might be worth explicitly checking and catching if you get L003 or L004

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/management/commands/utils/_multiqc.py` line 490 at r1](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-NyL5UwdEMlQALo7gbxp:-NyPYJhO-0Ir3vWzzby6:b-1hvby9) ([raw file](https://github.com/eastgenomics/trendyQC/blob/c4d6f40d88bf5b28c7bbb481471068822cded9a9/trendyqc/trend_monitoring/management/commands/utils/_multiqc.py#L490)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I don't think we've got to S4 yet routinely for WES, might be worth explicitly checking and catching if you get L003 or L004
</blockquote></details>

Added warning message, the import should fail because of the IntegrityError at line 554

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-:-NyPdaxA5RW6PjTClyq4:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-:-NyPddRZB6Mu-9v59gx7:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/90#-:-NyPdeMnCoykhlogc8sX:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
